# Generated by Django 4.1 on 2026-04-15 17:18

import django.core.validators
from django.db import migrations, models
import scams.models


class Migration(migrations.Migration):

    dependencies = [
        ('scams', '0005_alter_scam_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scam',
            name='date_seen',
        ),
        migrations.RemoveField(
            model_name='scam',
            name='url_or_contact',
        ),
        migrations.AlterField(
            model_name='scam',
            name='amount_lost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='scam',
            name='date_occurred',
            field=models.DateField(blank=True, null=True, validators=[scams.models.validate_not_future]),
        ),
        migrations.AlterField(
            model_name='scam',
            name='reporter_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='scam',
            name='scam_type',
            field=models.CharField(choices=[('financial', 'Financial transfer scams'), ('identity', 'Identity and impersonation scams'), ('investment', 'Investment and wealth scams'), ('other', 'Other scams')], max_length=100),
        ),
    ]
