# Generated by Django 4.2.30 on 2026-05-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scams', '0006_remove_scam_date_seen_remove_scam_url_or_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scam',
            name='url_or_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scam',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone call'), ('sms', 'SMS'), ('email', 'Email'), ('mail', 'Mail'), ('social', 'Social media'), ('messaging', 'Messaging app'), ('website', 'Website / ad'), ('in_person', 'In person approach'), ('other', 'Other channel')], default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='scam',
            name='scam_type',
            field=models.CharField(choices=[('financial', 'Financial transfer scams'), ('identity', 'Identity and impersonation scams'), ('investment', 'Investment and wealth scams'), ('other', 'Other scams')], default='undefined', max_length=100),
        ),
    ]
