# Generated by Django 4.2.30 on 2026-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scams', '0007_scam_url_or_contact_alter_scam_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scam',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('CAD', 'CAD — Canadian Dollar'), ('INR', 'INR — Indian Rupee'), ('MXN', 'MXN — Mexican Peso'), ('NGN', 'NGN — Nigerian Naira'), ('ZAR', 'ZAR — South African Rand'), ('BRL', 'BRL — Brazilian Real'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('Other', 'Other')], max_length=10),
        ),
    ]
